# watcher.py

WATCHLIST = [
    # KOLs
    {"handle": "@RoundtableSpace", "type": "kol"},
    {"handle": "@0xyoussea", "type": "kol"},
    {"handle": "@igoryuzo", "type": "kol"},
    {"handle": "@0xDeployer", "type": "kol"},
    {"handle": "@runn3rrr", "type": "kol"},
    {"handle": "@ShaneMa", "type": "kol"},
    {"handle": "@Nick_Prince12", "type": "kol"},
    {"handle": "@QuigleyNFT", "type": "kol"},
    {"handle": "@icobeast", "type": "kol"},
    {"handle": "@waleswoosh", "type": "kol"},
    {"handle": "@oxtochi", "type": "kol"},
    {"handle": "@zachxbt", "type": "kol"},
    {"handle": "@steipete", "type": "kol"},
    {"handle": "@sharbel", "type": "kol"},
    {"handle": "@nix_eth", "type": "kol"},
    {"handle": "@felixrieseberg", "type": "kol"},
    {"handle": "@iwantlambo", "type": "kol"},
    {"handle": "@austingriffith", "type": "kol"},
    {"handle": "@MattPRD", "type": "kol"},
    {"handle": "@cassidoo", "type": "kol"},
    {"handle": "@_davideast", "type": "kol"},
    {"handle": "@Th0rgal_", "type": "kol"},
    {"handle": "@max_sixty", "type": "kol"},
    {"handle": "@natebrake", "type": "kol"},
    {"handle": "@mitchellh", "type": "kol"},
    {"handle": "@TedPillows", "type": "kol"},
    {"handle": "@AlexPalcuie", "type": "kol"},
    {"handle": "@alistaiir", "type": "kol"},
    {"handle": "@0xSigil", "type": "kol"},
    {"handle": "@neynarxyz", "type": "kol"},

    # AI agents / bots
    {"handle": "@moltbook", "type": "agent"},
    {"handle": "@moltlaunch", "type": "agent"},
    {"handle": "@moltxio", "type": "agent"},
    {"handle": "@clawdbotatg", "type": "agent"},
    {"handle": "@AntiHunterAI", "type": "agent"},
    {"handle": "@AtlasForgeAI", "type": "agent"},
    {"handle": "@claudeai", "type": "agent"},
    {"handle": "@openclaw", "type": "agent"},
    {"handle": "@Clawnch_Bot", "type": "agent"},
    {"handle": "@clanker_world", "type": "agent"},
    {"handle": "@Base_Insights", "type": "agent"},
    {"handle": "@virtuals_io", "type": "agent"},
    {"handle": "@AIonBase_", "type": "agent"},
    {"handle": "@base", "type": "org"},
    {"handle": "@BaseHubHB", "type": "org"},
    {"handle": "@ConwayResearch", "type": "agent"},
    {"handle": "@JunoAgent", "type": "agent"},
    {"handle": "@clawk_ai", "type": "agent"},
    {"handle": "@Clawmode", "type": "agent"},
    {"handle": "@KellyClaudeAI", "type": "agent"},
]
